-- Python4Physics v2 Database Schema Migration
-- Generated: 2026-09-22 14:13:28

DROP TABLE IF EXISTS `p4p_menus`;
CREATE TABLE `p4p_menus` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `language` varchar(20) NOT NULL,
  `menu_id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `sort_order` int(11) DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_lang_menu` (`language`,`menu_id`)
) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('1', 'python', '1', 'Introduction to Python', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('2', 'python', '2', 'Iterable Data Type', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('3', 'python', '3', 'Basic Python Programs', '3', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('4', 'python', '4', 'Matrix Operation', '4', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('5', 'python', '5', 'Plotting in Python', '5', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('6', 'python', '6', 'Ordinary Differential Equation-1', '6', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('7', 'python', '7', 'Introduction to Numpy', '7', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('8', 'python', '8', 'Solve Linear Equations', '8', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('9', 'python', '9', 'Introduction to Scipy', '9', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('10', 'python', '10', 'Interpolation', '10', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('11', 'python', '11', 'Numerical Integration', '11', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('12', 'python', '12', 'Ordinary Differential Equation-2', '12', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('13', 'python', '13', 'Curve Fitting', '13', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('14', 'python', '14', 'Special Functions', '14', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('15', 'python', '15', 'Fourier Series', '15', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('16', 'python', '16', 'Partial Differential Equations', '16', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('17', 'python', '17', 'Shooting Method for Boundary Value Problem', '17', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('18', 'python', '18', 'TISE Solution', '18', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('19', 'python', '19', 'TDSE Solution', '19', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('20', 'python', '20', 'Application in Statistical Mechanics', '20', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('21', 'gnuplot', '1', 'Plot of 2D Graph', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('22', 'gnuplot', '2', 'User Defined Function Plot', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('23', 'gnuplot', '3', 'Data File Plot', '3', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('24', 'gnuplot', '4', 'Data Fitting', '4', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('25', 'gnuplot', '5', 'Special Plot', '5', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('26', 'latex', '1', 'Introduction to Latex', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('27', 'latex', '2', 'Document Classes', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('28', 'latex', '3', 'Page Layout and Sectioning', '3', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('29', 'latex', '4', 'List Structure', '4', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('30', 'latex', '5', 'Fonts and Size', '5', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('31', 'latex', '6', 'Mathematical Representations', '6', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('32', 'latex', '7', 'Creating Tables', '7', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('33', 'latex', '8', 'Figures', '8', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('34', 'latex', '9', 'Bibliography', '9', '2026-09-22 16:28:18');
INSERT INTO `p4p_menus` (`id`, `language`, `menu_id`, `title`, `sort_order`, `created_at`) VALUES ('35', 'latex', '10', 'Graphics', '10', '2026-09-22 16:28:18');

DROP TABLE IF EXISTS `p4p_submenus`;
CREATE TABLE `p4p_submenus` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `language` varchar(20) NOT NULL,
  `menu_id` int(11) NOT NULL,
  `submenu_id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `sort_order` int(11) DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_lang_menu_sub` (`language`,`menu_id`,`submenu_id`)
) ENGINE=InnoDB AUTO_INCREMENT=142 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('1', 'python', '1', '1', 'Print Function', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('2', 'python', '1', '2', 'Variable and Data Types', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('3', 'python', '1', '3', 'Mathematical Operations', '3', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('4', 'python', '1', '4', 'Conditionals (if, elif, else)', '4', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('5', 'python', '1', '5', 'For Loop', '5', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('6', 'python', '1', '6', 'While Loop', '6', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('7', 'python', '1', '7', 'User Defined Function', '7', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('8', 'python', '1', '8', 'Module math and cmath', '8', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('9', 'python', '1', '9', 'I/O Operation', '9', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('10', 'python', '2', '1', 'List', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('11', 'python', '2', '2', 'Tuple', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('12', 'python', '2', '3', 'String', '3', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('13', 'python', '3', '1', 'Series Expansion', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('14', 'python', '3', '2', 'Determining Whether an Integer is Prime or Not', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('15', 'python', '3', '3', 'Finding Prime Number Greater or Lesser Than a Given Value', '3', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('16', 'python', '3', '4', 'Finding All Prime Numbers Within a Given Range', '4', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('17', 'python', '3', '5', 'Root Finding', '5', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('18', 'python', '3', '6', 'Sorting', '6', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('19', 'python', '3', '7', 'Finding Factors of an Integer', '7', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('20', 'python', '3', '8', 'Miscellaneous Problems', '8', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('21', 'python', '4', '1', 'Matrix', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('22', 'python', '4', '2', 'Matrix Addition', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('23', 'python', '4', '3', 'Matrix Multiplication', '3', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('24', 'python', '4', '4', 'Matrix Transpose', '4', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('25', 'python', '4', '5', 'Matrix Determinant', '5', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('26', 'python', '4', '6', 'Matrix using List Comprehension', '6', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('27', 'python', '5', '1', 'Basic Plot and formatting', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('28', 'python', '5', '2', 'Subplot, Multiplot', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('29', 'python', '5', '3', 'Colormaps in Plots', '3', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('30', 'python', '5', '4', 'Bar Plot', '4', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('31', 'python', '5', '5', 'Pie Chart', '5', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('32', 'python', '5', '6', 'Histogram', '6', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('33', 'python', '5', '7', 'Quiver plot to show Vector Fields', '7', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('34', 'python', '5', '8', 'Stream plot to Visualize Flow Data', '8', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('35', 'python', '5', '9', 'Polar, Parametric Plot', '9', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('36', 'python', '5', '10', 'Contour Plot', '10', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('37', 'python', '5', '11', '3D Plot', '11', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('38', 'python', '5', '12', 'Density Plot', '12', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('39', 'python', '5', '13', 'Animated Plot', '13', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('40', 'python', '5', '14', 'Miscellaneous', '14', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('41', 'python', '6', '1', 'Euler Algorithm', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('42', 'python', '6', '2', 'Motion of a Harmonic Oscillator', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('43', 'python', '6', '3', 'Capacitor Charging / Discharging', '3', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('44', 'python', '6', '4', 'Half Wave Rectifier with Capacitor Filter', '4', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('45', 'python', '7', '1', 'Introduction to Numpy', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('46', 'python', '7', '2', 'Array Creation', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('47', 'python', '7', '3', 'Array Inspection', '3', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('48', 'python', '7', '4', 'Mathematical Operation', '4', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('49', 'python', '7', '5', 'Array Indexing and Slicing', '5', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('50', 'python', '7', '6', 'Numpy for Matrix Operators', '6', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('51', 'python', '7', '7', 'Linear Algebra', '7', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('52', 'python', '8', '1', 'Gauss Elimination', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('53', 'python', '8', '2', 'Using numpy linalg module', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('54', 'python', '8', '3', 'Gauss-Seidel Method', '3', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('55', 'python', '9', '1', 'Integration', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('56', 'python', '9', '2', 'Interpolation', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('57', 'python', '9', '3', 'Linear Algebra', '3', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('58', 'python', '9', '4', 'Optimization', '4', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('59', 'python', '10', '1', 'Lagrange’s Interpolation', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('60', 'python', '10', '2', 'Newton’s Forward and Backward Interpolation', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('61', 'python', '11', '1', 'Trapezoidal Method', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('62', 'python', '11', '2', 'Simpson’s 1/3rd Rule', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('63', 'python', '11', '3', 'Gaussian Quadrature method', '3', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('64', 'python', '11', '4', 'Convolution of two Gaussian Functions', '4', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('65', 'python', '12', '1', '1st Order ODE (RK2 Method)', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('66', 'python', '12', '2', '2nd Order ODE (RK2 Method)', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('67', 'python', '12', '3', '1st Order ODE (RK4 Method)', '3', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('68', 'python', '12', '4', '2nd Order ODE (RK4 Method)', '4', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('69', 'python', '12', '5', 'Solve ODE using scipy.integrate.odeint()', '5', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('70', 'python', '13', '1', 'Using Numpy', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('71', 'python', '13', '2', 'Using Scipy.optimize', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('72', 'python', '14', '1', 'Bessel Function', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('73', 'python', '14', '2', 'Legendre Polynomial', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('74', 'python', '14', '3', 'Hermite Polynomial', '3', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('75', 'python', '15', '1', 'Square Wave', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('76', 'python', '15', '2', 'Triangular Wave', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('77', 'python', '15', '3', 'Sawtooth Wave', '3', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('78', 'python', '16', '1', 'Heat Diffusion', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('79', 'python', '16', '2', 'Laplace Equation', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('80', 'python', '16', '3', 'Wave Equation', '3', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('81', 'python', '16', '4', 'Schrodinger Equation', '4', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('82', 'python', '17', '1', 'Example-1', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('83', 'python', '17', '2', 'Example-2', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('84', 'python', '18', '1', 'Shooting Method to Solve TISE', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('85', 'python', '18', '2', 'Particle in 1D Potential Box', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('86', 'python', '18', '3', 'Finite Square Well', '3', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('87', 'python', '18', '4', 'Harmonic Oscillator', '4', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('88', 'python', '18', '5', 'H-like Atom', '5', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('89', 'python', '18', '6', 'Particle in 1D Potential Well (Solving Transcendental Equation)', '6', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('90', 'python', '18', '7', 'TISE by Finite Difference Method', '7', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('91', 'python', '19', '1', 'Explicit Methods', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('92', 'python', '19', '2', 'Implicit Methods', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('93', 'python', '19', '3', 'Crank-Nicolson Methods', '3', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('94', 'python', '19', '4', 'Time Evaluation of WavePacket', '4', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('95', 'python', '19', '5', 'Barrier Penetration and Tunneling for an Initially Gaussian Wavepacket', '5', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('96', 'python', '20', '1', 'Study of Random Numbers and Time Series', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('97', 'python', '20', '2', 'Generate Different Variate from Uniform Variate', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('98', 'python', '20', '3', 'Coin Tossing Simulation', '3', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('99', 'python', '20', '4', 'Nuclear Decay Simulation', '4', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('100', 'python', '20', '5', '1D Random Walk Simulation', '5', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('101', 'python', '20', '6', '2D Random Walk Simulation', '6', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('102', 'python', '20', '7', 'Monte Carlo Method', '7', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('103', 'python', '20', '8', 'Specific Heat of Solids (Einstein’s Theory)', '8', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('104', 'python', '20', '9', 'Specific Heat of Solids (Debye’s Theory)', '9', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('105', 'python', '20', '10', 'Plots of Different Distribution Functions', '10', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('106', 'gnuplot', '1', '1', 'Function Plot', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('107', 'gnuplot', '1', '2', 'Data File Plot', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('108', 'gnuplot', '2', '1', 'Function Plot', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('109', 'gnuplot', '2', '2', 'Piecewise Function Plot', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('110', 'gnuplot', '3', '1', 'Conditional Plotting of Data File', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('111', 'gnuplot', '4', '1', 'Fitting Data Files Using Gnuplot', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('112', 'gnuplot', '5', '1', 'Polar Plot', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('113', 'gnuplot', '5', '2', 'Parametric Plot', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('114', 'latex', '1', '1', 'Basic LaTeX File', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('115', 'latex', '2', '1', 'Report Class', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('116', 'latex', '2', '2', 'Article Class', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('117', 'latex', '2', '3', 'Book Class', '3', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('118', 'latex', '3', '1', 'Page Layout', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('119', 'latex', '3', '2', 'Document Sectioning', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('120', 'latex', '4', '1', 'Item List', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('121', 'latex', '4', '2', 'Enumerate List', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('122', 'latex', '4', '3', 'Description List', '3', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('123', 'latex', '5', '1', 'Font Types', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('124', 'latex', '5', '2', 'Font Sizes', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('125', 'latex', '6', '1', 'Symbols and Special Characters', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('126', 'latex', '6', '2', 'Mathematical Functions', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('127', 'latex', '6', '3', 'Mathematical Equations', '3', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('128', 'latex', '6', '4', 'Calculus', '4', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('129', 'latex', '6', '5', 'Matrices', '5', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('130', 'latex', '7', '1', 'Table Create', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('131', 'latex', '7', '2', 'Table Borders', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('132', 'latex', '7', '3', 'Table Formatting', '3', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('133', 'latex', '8', '1', 'Inserting Figures', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('134', 'latex', '8', '2', 'Figure Alignment', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('135', 'latex', '8', '3', 'Figure Captions', '3', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('136', 'latex', '9', '1', 'Basic Bibliography', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('137', 'latex', '9', '2', 'Bibliography Styles', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('138', 'latex', '10', '1', 'Quotations', '1', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('139', 'latex', '10', '2', 'TikZ Pictures', '2', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('140', 'latex', '10', '3', 'Drawing Curves and Shapes', '3', '2026-09-22 16:28:18');
INSERT INTO `p4p_submenus` (`id`, `language`, `menu_id`, `submenu_id`, `title`, `sort_order`, `created_at`) VALUES ('141', 'latex', '10', '4', 'Coloring', '4', '2026-09-22 16:28:18');

DROP TABLE IF EXISTS `assignments`;
CREATE TABLE `assignments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `category` varchar(50) NOT NULL DEFAULT 'mechanics',
  `title` varchar(255) NOT NULL,
  `subtitle` varchar(255) DEFAULT '',
  `description` text DEFAULT NULL,
  `theory_equations` text DEFAULT NULL,
  `parameters` text DEFAULT NULL,
  `starter_code` longtext DEFAULT NULL,
  `solution_code` longtext DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `assignments` (`id`, `category`, `title`, `subtitle`, `description`, `theory_equations`, `parameters`, `starter_code`, `solution_code`, `created_at`, `updated_at`) VALUES ('1', 'mechanics', 'Projectile Motion with Quadratic Air Drag', 'Model aerodynamic deceleration using coupled ODEs', 'Model the trajectory of a spherical projectile under the influence of gravity and non-linear aerodynamic air resistance.', '$$\\frac{dx}{dt} = v_x, \\quad \\frac{dv_x}{dt} = -\\frac{c}{m} v_x \\sqrt{v_x^2 + v_y^2}$$\\n$$\\frac{dy}{dt} = v_y, \\quad \\frac{dv_y}{dt} = -g -\\frac{c}{m} v_y \\sqrt{v_x^2 + v_y^2}$$', 'Mass $m = 0.145\\text{ kg}$, initial speed $v_0 = 45\\text{ m/s}$, launch angle $\\theta = 45^\\circ$, drag constant $c = 0.0015\\text{ kg/m}$, $g = 9.81\\text{ m/s}^2$.', 'import numpy as np\nimport matplotlib.pyplot as plt\n\nm = 0.145\ng = 9.81\nc = 0.0015\nv0 = 45.0\ntheta = np.radians(45)\n\ndt = 0.001\nx, y = [0.0], [0.0]\nvx, vy = [v0 * np.cos(theta)], [v0 * np.sin(theta)]\n\nwhile y[-1] >= 0:\n    v = np.sqrt(vx[-1]**2 + vy[-1]**2)\n    ax = -(c/m) * v * vx[-1]\n    ay = -g - (c/m) * v * vy[-1]\n    vx.append(vx[-1] + ax * dt)\n    vy.append(vy[-1] + ay * dt)\n    x.append(x[-1] + vx[-1] * dt)\n    y.append(y[-1] + vy[-1] * dt)\n\nR_vac = (v0**2 * np.sin(2*theta)) / g\nprint(f\"Vacuum Range: {R_vac:.2f} m\")\nprint(f\"Realistic Range (Drag): {x[-1]:.2f} m\")\n\nplt.figure(figsize=(7, 3.8))\nplt.plot(x, y, label=\'With Quadratic Drag\', color=\'#06b6d4\', lw=2)\nplt.title(\'Projectile Motion with Air Drag\')\nplt.xlabel(\'Distance (m)\')\nplt.ylabel(\'Height (m)\')\nplt.grid(True, alpha=0.3)\nplt.legend()\nplt.show()', '', '2026-09-22 16:28:18', '2026-09-22 16:28:18');
INSERT INTO `assignments` (`id`, `category`, `title`, `subtitle`, `description`, `theory_equations`, `parameters`, `starter_code`, `solution_code`, `created_at`, `updated_at`) VALUES ('2', 'electrodynamics', 'Electric Field & Equipotential Contours of an Electric Quadrupole', '2D electrostatic field line integration and potential mesh computation', 'Calculate and visualize the 2D electrostatic potential field $\\Phi(x, y)$ and field vector gradient $\\vec{E} = -\\nabla \\Phi$ for an arrangement of four point charges in a planar quadrupole configuration.', '$$\\Phi(\\vec{r}) = \\frac{1}{4\\pi \\varepsilon_0} \\sum_{i=1}^{N} \\frac{q_i}{|\\vec{r} - \\vec{r}_i|}, \\quad \\vec{E} = -\\nabla \\Phi = -\\left( \\frac{\\partial \\Phi}{\\partial x} \\hat{i} + \\frac{\\partial \\Phi}{\\partial y} \\hat{j} \\right)$$', 'Charges $q = \\pm 1\\text{ nC}$ placed at $(1, 1), (-1, 1), (-1, -1), (1, -1)$. Mesh resolution $200 \\times 200$.', 'import numpy as np\nimport matplotlib.pyplot as plt\n\nx = np.linspace(-3, 3, 200)\ny = np.linspace(-3, 3, 200)\nX, Y = np.meshgrid(x, y)\n\ncharges = [\n    {\'q\':  1.0, \'pos\': ( 1.0,  1.0)},\n    {\'q\': -1.0, \'pos\': (-1.0,  1.0)},\n    {\'q\':  1.0, \'pos\': (-1.0, -1.0)},\n    {\'q\': -1.0, \'pos\': ( 1.0, -1.0)},\n]\n\nV = np.zeros_like(X)\nfor c in charges:\n    r = np.sqrt((X - c[\'pos\'][0])**2 + (Y - c[\'pos\'][1])**2)\n    r = np.maximum(r, 0.15)\n    V += c[\'q\'] / r\n\nEy, Ex = np.gradient(-V, y, x)\n\nplt.figure(figsize=(7, 4.5))\nplt.contourf(X, Y, V, levels=30, cmap=\'RdBu_r\', alpha=0.7)\nplt.colorbar(label=\'Potential V (arb. units)\')\nplt.streamplot(X, Y, Ex, Ey, color=\'black\', density=0.9, linewidth=0.7)\nplt.title(\'Quadrupole Potential & Electric Field Lines\')\nplt.xlabel(\'x\')\nplt.ylabel(\'y\')\nplt.show()', '', '2026-09-22 16:28:18', '2026-09-22 16:28:18');
INSERT INTO `assignments` (`id`, `category`, `title`, `subtitle`, `description`, `theory_equations`, `parameters`, `starter_code`, `solution_code`, `created_at`, `updated_at`) VALUES ('3', 'quantum', 'Finite Square Well: Bound State Energies via Transcendental Bisection', 'Numerical root finding for symmetric and antisymmetric quantum wavefunctions', 'Determine the bound-state energy eigenvalues for a particle of mass $m$ trapped inside a finite 1D square potential well of width $2a$ and depth $V_0$.', '$$\\xi \\tan \\xi = \\sqrt{\\xi_0^2 - \\xi^2} \\quad \\text{(Even Parity)}, \\quad -\\xi \\cot \\xi = \\sqrt{\\xi_0^2 - \\xi^2} \\quad \\text{(Odd Parity)}$$\\n$$\\text{where } \\xi = \\frac{a}{\\hbar}\\sqrt{2m(E + V_0)}, \\quad \\xi_0 = \\frac{a}{\\hbar}\\sqrt{2m V_0}$$', 'Well half-width $a = 1.0\\text{ nm}$, Well depth $V_0 = 10.0\\text{ eV}$, electron mass $m_e$.', 'import numpy as np\nfrom scipy.optimize import brentq\nimport matplotlib.pyplot as plt\n\nV0 = 10.0 # eV\na = 1.0e-9 # m\nhbar = 1.0545718e-34\nm = 9.10938356e-31\ne = 1.60217663e-19\n\nxi0 = (a / hbar) * np.sqrt(2 * m * V0 * e)\nprint(f\"Dimensionless parameter xi_0 = {xi0:.3f}\")\n\ndef even_eq(xi):\n    return xi * np.tan(xi) - np.sqrt(xi0**2 - xi**2)\n\nroots = []\nxi_vals = np.linspace(0.01, min(xi0 - 0.01, 3*np.pi), 500)\nfor i in range(len(xi_vals)-1):\n    x1, x2 = xi_vals[i], xi_vals[i+1]\n    if np.cos(x1)*np.cos(x2) > 0 and even_eq(x1)*even_eq(x2) < 0:\n        try:\n            r = brentq(even_eq, x1, x2)\n            roots.append(r)\n        except:\n            pass\n\nprint(f\"Found {len(roots)} even bound states:\")\nfor idx, r in enumerate(roots, 1):\n    E_bound = (r / xi0)**2 * V0 - V0\n    print(f\"  E_{idx} = {E_bound:.3f} eV\")', '', '2026-09-22 16:28:18', '2026-09-22 16:28:18');
INSERT INTO `assignments` (`id`, `category`, `title`, `subtitle`, `description`, `theory_equations`, `parameters`, `starter_code`, `solution_code`, `created_at`, `updated_at`) VALUES ('4', 'thermo', '2D Ising Model Monte Carlo via Metropolis Algorithm', 'Spontaneous symmetry breaking, magnetization, and phase transition simulation', 'Simulate the magnetic phase transition in a 2D ferromagnetic square lattice using the Metropolis Monte Carlo algorithm.', '$$\\mathcal{H} = -J \\sum_{\\langle i, j \\rangle} s_i s_j, \\quad \\Delta E = 2 J s_i \\sum_{\\text{neighbors}} s_j$$\\n$$P(\\text{flip}) = \\min\\left(1, e^{-\\Delta E / k_B T}\\right)$$', 'Lattice size $L = 32 \\times 32$, Coupling $J = 1.0$, $T_c \\approx 2.269$.', 'import numpy as np\nimport matplotlib.pyplot as plt\n\nL = 32\nN_steps = 15000\nT = 2.0\n\nspins = np.random.choice([-1, 1], size=(L, L))\n\ndef step(spins, T):\n    for _ in range(L * L):\n        i = np.random.randint(0, L)\n        j = np.random.randint(0, L)\n        s = spins[i, j]\n        nb = spins[(i+1)%L, j] + spins[(i-1)%L, j] + spins[i, (j+1)%L] + spins[i, (j-1)%L]\n        dE = 2 * s * nb\n        if dE <= 0 or np.random.rand() < np.exp(-dE / T):\n            spins[i, j] = -s\n    return spins\n\nfor _ in range(50):\n    spins = step(spins, T)\n\nplt.figure(figsize=(5, 5))\nplt.imshow(spins, cmap=\'coolwarm\', interpolation=\'nearest\')\nplt.title(f\'2D Ising Lattice at T = {T:.2f}\')\nplt.colorbar(ticks=[-1, 1], label=\'Spin Orientation\')\nplt.axis(\'off\')\nplt.show()', '', '2026-09-22 16:28:18', '2026-09-22 16:28:18');

DROP TABLE IF EXISTS `admin_users`;
CREATE TABLE `admin_users` (
  `admin_id` int(11) NOT NULL,
  `fac_id` int(11) NOT NULL,
  `name` char(50) NOT NULL DEFAULT '',
  `nickname` char(20) NOT NULL DEFAULT '',
  `mobilenumber` char(20) NOT NULL DEFAULT '',
  `department` char(50) NOT NULL DEFAULT '',
  `dept_id` char(10) NOT NULL DEFAULT '',
  `email` char(50) NOT NULL,
  `username` char(20) NOT NULL DEFAULT '',
  `password_text` varchar(20) NOT NULL,
  `password` varchar(150) NOT NULL,
  `otp` varchar(10) NOT NULL,
  `is_verified` varchar(10) NOT NULL,
  `created_date` varchar(20) NOT NULL,
  `usergroup` int(11) NOT NULL,
  `deptgroup` int(11) NOT NULL,
  `status` char(10) NOT NULL DEFAULT '',
  `is_superuser` char(10) NOT NULL DEFAULT ''
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('1', '11111', 'Dr S Sahoo', 'principal', '7980548100', '', '', 'dr_s_sahoo@yahoo.com', 'principal', 'swap0101', '$2y$10$6cQj7IQp.CkmkYcNPcBqF.HO.kDbS7it62O7Ao7SU3QDhxXzBfFta', '368080', '1', '2025-10-14 21:18:47', '0', '0', '1', '1');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('2', '1101', 'M Rahaman', 'mossior', '9830176345', 'Physics', '11', 'mossior.rahaman@gmail.com', 'mossior', 'Moss@123', '$2y$10$/5vY98SBq/wJweoulf/MMOdGuXnJaqUSd8g5Y5pShdCqLlS/8M2my', '488487', '1', '2025-11-09 13:28:55', '0', '0', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('3', '6666', 'Barababu', '', '', '', '', 'dchcollege@yahoo.com', 'office', 'Office@123', '$2y$10$ys1kJ3mPUoQF5/II17lNM.3zrSX0/jjCwzOgYGZS/bj6NghuWnGbC', '152515', '1', '2025-10-16 03:26:40', '0', '0', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('4', '1', 'Sovona', 'sovona', '8981492223', 'Bengali', '1', 'h', 'SOVONA', 'sov#ben20', '$2y$10$HnznVE5RI2WFt43WGqoMXuHEQvYttWxmWX6BeRstzr/toe83XWUl.', '', '1', '24-08-2020 14:31', '2', '1', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('5', '74', 'TARAK DEY', 'tarak', '9123994547', 'Commerce', '18', 't', 'TARAK_DEY', 'tdey#com20', '$2y$10$N/.HIKhkGpM5FCmhK5YSuuxmNBaiRclNPIUWIYilSJ8Yv2rPKhzPe', '', '1', '24-08-2020 14:44', '2', '18', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('6', '2', 'PRODIP BAIDYA', 'prodip', '', 'Bengali', '1', 's', 'PRODIP-PB', 'pb#beng20', '$2y$10$954Sh99rZVWU6F7PAXEXZ.uTqXOnprKlCggeqXJcE67gg2AU7MpV6', '', '1', '24-08-2020 22:30', '2', '1', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('7', '1202', 'PARTHA BISWAS', 'partha', '96744 54351', 'Chemistry', '12', 'h', 'PARTHA-PB', 'pb#chem20', '$2y$10$DOOvTRlhxsykSgS546tVcecAjSvezqrQXNFAvj3BjoqQgY137jIBC', '', '1', '24-08-2020 21:56', '2', '12', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('8', '75', 'KUSHAL DE', 'kushal', '9831506070', 'Commerce', '18', 'd', 'KUSHAL_DE', 'kus#com20', '$2y$10$qPmsAVdBrlXtlce2wurfnecdYiNtbiGMKJdcRcmZzmmpgh9C0pZC.', '', '1', '24-08-2020 14:49', '2', '18', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('10', '704', 'DEBKUMAR', 'debkumar', '7699300877', 'Education', '7', 'h', 'Debkumar', 'Debkumar', '$2y$10$z3u4SWRNQVxY9ZoCgPR.YeJAlNj6kpR3NeMgs48ZGEri4JbS0LfEm', '', '1', '15-08-2022 09:43', '2', '7', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('11', '3', 'RIZWANA NASIRA', 'rizwana', '8250406134', 'Bengali', '1', 'r', 'RIZWANA-RN', 'rn#beng20', '$2y$10$L6bC3Pq6n7mTRd0mWCkEau85FhUgQoDt4Sx62Igx77tGG37dw6JVm', '', '1', '24-08-2020 22:32', '2', '1', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('12', '701', 'PRABIR GHOSH', 'prabir', '9875455540', 'Education', '7', 'h', 'PRABIR-PG', 'pg#edu20', '$2y$10$ppF/hgi2f2xPYDW1xOaADuNyYnV72KKTonKILKV2Lf7XcrIYJ9Zq6', '', '1', '24-08-2020 21:32', '2', '7', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('13', '12', 'BULA RANI HOWLADER', 'bula', '', 'English', '2', 'b', 'BULA-BH', 'bh#eng20', '$2y$10$qg73pT/ThIDeqm8nr1JLceU3I.SH/suCigQnaMNuzz/TIAUm/55E.', '', '1', '24-08-2020 23:10', '2', '2', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('14', '901', 'BRATATI DEY', 'bratati', '9830674370', 'Geography', '9', 'h', 'BRATATI-BD', 'bd#geo20', '$2y$10$oE/xqdyuDUm6EUsFraTZ5OZy83xyIT5xcaLIkDQKIKdRgenLd6Ooa', '', '1', '24-08-2020 21:59', '2', '9', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('15', '904', 'KAMAL HOSSAIN AKHAND', 'kamal', '9836794210', 'Geography', '9', 'k', 'KAMAL-HA', 'ka#geo20', '$2y$10$qdyDoPNxnphFyhdFERvioeq1Z2R4ITmsHY1rJTak2k.PNk1.tguAS', '', '1', '25-08-2020 08:50', '2', '9', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('16', '64', 'RANJIT MISHRA', 'ranjit', '94770 42914', 'Mathematics', '13', 'r', 'RANJIT-RM', 'rm#math20', '$2y$10$t.ewfjU9v8m1WdBQUrl0XeIo.9uQZtFzGis.v0ZJDKt87qmbVUXjG', '', '1', '25-08-2020 19:06', '2', '13', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('17', '1602', 'MALINI BASU', 'malini', '', 'Microbiology', '16', 'h', 'MALINI-MB', 'mb#micr20', '$2y$10$h73qkClGSnK836.rmg8fTObZ5kizehH5nwmlhvMYhxnHuALHL6At2', '', '1', '24-08-2020 22:07', '2', '16', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('18', '602', 'MANAS MANDAL', 'manas', '79805 24448', 'Philosophy', '6', 'm', 'MANAS-MM', 'mm#phil20', '$2y$10$Kg3rcgPfltR9J6hCzXlSXuPoTHm.ihU0t4NhxMa1N/RrbFmHcBDEi', '', '1', '24-08-2020 20:47', '2', '6', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('19', '506', 'KAMAL HALDER', 'kamal', '', 'Political Science', '5', 'k', 'KAMAL-KH', 'kh#pol20', '$2y$10$08Bl74Tn5wujQY5Zg/OrVe8LmMuGk5OTBt8QJMt/DHTng8.PVeWeC', '', '1', '26-08-2020 08:49', '2', '5', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('20', '501', 'MANIKA RAKSHIT', 'manika', '9830291367', 'Political Science', '5', 'm', 'MANIKA-MR', 'mr#pol20', '$2y$10$6hAbMfqVmoWF0cHW38euzOAa3I1q/HFl2LuEZaegn1JELbtftMYKy', '', '1', '25-08-2020 00:16', '2', '5', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('21', '502', 'SUBIR GAYEN', 'subir', '82969 80073', 'Political Science', '5', 's', 'SUBIR-SG', 'sg#pol20', '$2y$10$XZbGoM2k94cdUE3Lh/9Dt.2cE9zubpiJJBK5YSQTEJxViQlV93bwC', '', '1', '24-08-2020 22:50', '2', '5', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('22', '905', 'PARUL DAS', 'parul', '', 'Geography', '9', 'p', 'PARUL-PD', 'pd#geo20', '$2y$10$wghn8B1M39YTdn9Pk0/KjetasJgMg64MWpG4t2UnV6vV3a8qBVMoq', '', '1', '25-08-2020 08:53', '2', '9', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('23', '1406', 'POULAMI SARANGI', 'poulami', '', 'Zoology', '14', 's', 'POULAMI-PS', 'ps#zool20', '$2y$10$X5BbIqW9hb9nBpLN0XhrXOjTFuWxftGMoB9uFyqmhljCgV408ofuC', '', '1', '25-08-2020 09:33', '2', '14', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('24', '906', 'PUJARINI', 'pujarini', '9836745866', 'Geography', '', 'p', 'Pujarini', 'Pujarini', '$2y$10$UNOD1QbZF/164E/iVQDB.u8b/W4T/Ntx0CgsV0vZaDC8MUr7qbZLa', '', '1', '15-08-2022 09:29', '2', '0', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('25', '610', 'SUKANTA DAS', 'sukanta', '95645 92979', 'Education', '6', 's', 'sukanta', 'sukanta@12', '$2y$10$c8B8hn00ygMWlbTyEeqQkeRp9CN63/Yy1MTvwT/0IvNYRutHePgm.', '', '1', '26-08-2020 06:31', '2', '6', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('26', '6668', 'Office', 'office', '', '', '', 'd', 'office', 'Office@23#', '$2y$10$ys1kJ3mPUoQF5/II17lNM.3zrSX0/jjCwzOgYGZS/bj6NghuWnGbC', '', '1', '2023-01-26 21:32:23', '2', '91', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('27', '21', 'LAKSMAN', 'laksman', '9647242540', 'History', '4', 'a', 'Laksman', 'Laks@23#', '$2y$10$E17etHEfgepDOZZJrBj7a.5X0K/ksZOzsOVLsRNMGztP4VBDielWK', '', '1', '2023-01-27 18:34:46', '2', '4', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('28', '425', 'Raju', 'raju', '', 'History', '4', 'aaa@bbb.ccc', 'RajuMistry', 'Raju@23#', '$2y$10$VxZozENLAxtMZg87mnnjce4UtEspyhaNYsAG36UQyGtPp8JXoTb0e', '', '1', '2023-01-27 20:03:22', '2', '4', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('30', '608', 'Kutubuddin Sk.', 'kutubuddin', '7003500431', 'Philosophy', '6', 'dchcollege@yahoo.com', 'KUTUB', 'Kutub@23#', '$2y$10$Pjm3f02eJrdyv4AO/9zG4uAzhxl.OViiv.XlYogQNhPVpmmeXU6/u', '', '1', '2023-01-31 11:31:38', '2', '6', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('31', '1110', 'PUSPITA', 'puspita', '8777396656', 'Physics', '11', 'aaa@bbb.ccc', 'Puspita', 'Puspita@23#', '$2y$10$PGgM/vZNVa0mobq6XGKYj.U/V/2PJsXwzgMptniUML3b5wdWWLG.C', '', '1', '2023-02-02 11:01:34', '2', '11', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('32', '1103', 'Anirban', 'anirban', '7003939962', 'Physics', '11', 'anirban.shaw@gmail.com', 'anirban', 'Anirban@23#', '$2y$10$1BNKWQDA0AlEIeYJziLjeO9AoQ/UQUXK4LwLzpPpkbbuTkqHleq9e', '', '1', '2023-02-03 15:05:01', '1', '11', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('33', '4', 'Achyutananda Biswas', 'achyutananda', '9874799033', 'Bengali', '1', 'dchcollege@yahoo.com', 'ACHYUT', 'ach#beng20', '$2y$10$byM63tAnyZNCQg9tv9Bj/Opgyh8HMV4Tnv.WJtGunk4kjSppF7Cwu', '', '1', '2023-02-07 16:47:10', '2', '1', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('34', '6', 'Rita Naskar', 'rita', '', 'Bengali', '1', 'dchcollege@yahoo.com', 'RITA-RN', 'ri#beng20', '$2y$10$ELmk8XayXSyuhOWQ4uGuT.AESuaKh4CfrSdAwBlZmDYws7Zv42kMG', '', '1', '2023-02-07 16:48:56', '2', '1', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('35', '9', 'Abhiram Sarder', 'abhiram', '97326 07312', 'Bengali', '1', 'dchcollege@yahoo.com', 'ABHIRAM-AS', 'ab#beng20', '$2y$10$t9iSpadjVNpy3Jc1khGE3uyMltXlfzl0PD7cehZT.ZBdQM.NryKYW', '', '1', '2023-02-07 16:50:27', '2', '1', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('36', '7', 'Kathakali Sengupta', 'kathakali', '8617039009', 'Bengali', '1', 'dchcollege@yahoo.com', 'KATHA-KS', 'kat#beng20', '$2y$10$8P9Br.ib8i2XbB3Jwuc.BeIYWkYYV2Ff6jHLWrl0G/KMsJJ9FeI.y', '', '1', '2023-02-07 16:51:47', '2', '1', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('37', '10', 'Sudakshina Sengupta', 'sudakshina', '9830036739', 'English', '2', 'dchcollege@yahoo.com', 'SUDAKSHINA-SS', 'su#eng21', '$2y$10$BB1k7qKJR/znInMyGK7n7ev7dKjpquFBhqOmlrdsv3H8s13G1QEJO', '', '1', '2023-02-07 17:05:30', '2', '2', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('38', '1401', 'Subhasree Thakur', 'subhasree', '9875503540\r\n', 'Zoology', '14', 'dchcollege@yahoo.com', 'SUBHASREE-ST', 'subh#zool18', '$2y$10$KT4B9ReQH6GIrRrb8na2b.ycSgnbt4x5m57bwzJKaIVPmJ8qQpUNm', '', '1', '2023-02-08 14:52:47', '2', '14', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('39', '1402', 'Rupanwita Sarkar', 'rupanwita', '', 'Zoology', '14', 'dchcollege@yahoo.com', 'RUPANWITA-RS', 'rup#zool19', '$2y$10$6Xkg/HVvl5ZI8Vid6Gm8B.Vsgr7Llli.5S3P0LwCJraz9jo0nJ/5i', '', '1', '2023-02-08 14:53:42', '2', '14', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('40', '1501', 'Rupa Acharya', 'rupa', '9831179103', 'Botany', '15', 'dchcollege@yahoo.com', 'RUPA-RA', 'rupa#bot18', '$2y$10$zLoZ6lHmC.osDPacza5tLe2CHHK0SkmF7KP9eDtYqX6aOLz9Cgwp.', '', '1', '2023-02-08 15:16:45', '2', '15', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('41', '1502', 'Mobina Parveen', 'mobina', '89005 02985', 'Botany', '15', 'dchcollege@yahoo.com', 'MOBINA-MP', 'mob#bot19', '$2y$10$HNaW2BiMc2RILjoSJUcovexUPV0w6Kho2ecvjbOdgZajaUQKKXcBG', '', '1', '2023-02-08 15:17:58', '2', '15', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('42', '1504', 'Swarnaditya Mondal', 'swarnaditya', '7980608286', 'Botany', '15', 'dchcollege@yahoo.com', 'SWARNA-SM', 'swar#bot20', '$2y$10$usdrFJIuQuxLFkhvKb.WvOn./0anBCBqTQ6OJCpXe8f75GgWwkPpa', '', '1', '2023-02-08 15:18:51', '2', '15', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('43', '1503', 'Tapas Kr. Maity', 'tapas', '', 'Botany', '15', 'dchcollege@yahoo.com', 'TAPAS-TKM', 'tap#bot21', '$2y$10$Xf4bjcWCtjYPVGkwDGzbdudE0GgK.O6fW6QzJ495f45E8cNDLM8Ji', '', '1', '2023-02-08 15:20:10', '2', '15', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('44', '1203', 'ANAMIKA SAHA', 'anamika', '90510 21797', 'Chemistry', '12', 's', 'ANAMIKA-AS', 'as#chem20', '$2y$10$GnTIrhOV8XQdP3e5COreOOM4FT3jXxQWwTMfcbnAGymOqpxDey4tK', '', '1', '24-08-2020 22:45', '2', '12', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('45', '1603', 'Nirza Moktan', 'nirza', '', 'Micro Biology', '16', 'dchcollege@yahoo.com', 'NIRZA-NM', 'nir#mic19', '$2y$10$Wl1QmRYTAV/8vvW0xAp9UeddAda2bGQ8fhe50Z8CUusuJika1qx3G', '', '1', '2023-02-08 15:23:00', '2', '16', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('46', '1604', 'Dipankar Roy', 'dipankar', '9088554922', 'Micro Biology', '16', 'dchcollege@yahoo.com', 'DIPANKAR-DR', 'dop#mic20', '$2y$10$4SHq4aRxXb2UOfDM8btJ1..sD/9r5HlmU9TnbYaJ3rX2MN8jp7dSG', '', '1', '2023-02-08 15:23:51', '2', '16', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('47', '1606', 'Pampa Bhattacharya', 'pampa', '', 'Micro Biology', '16', 'dchcollege@yahoo.com', 'PAMPA-PB', 'pam#mic21', '$2y$10$fJqFkHQFobj2f87zCMtkcuH1ajGw2SgabTMkXTnX/fAIDzUE92VCe', '', '1', '2023-02-08 15:24:49', '2', '16', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('48', '902', 'Pijush K. Mondal', 'pijush', '9474151089', 'Geography', '9', 'dchcollege@yahoo.com', 'PIJUSH-PKM', 'pij#geo23', '$2y$10$g69R7R9hdLt2OoOi66s8/uiILhYsaygviqy5NVeWaPtb1kAiyDrYK', '', '1', '2023-02-09 13:08:07', '2', '9', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('49', '1301', 'Susanta Kr. Saha', 'susanta', '9433366577', 'Mathematics', '13', 'dchcollege@yahoo.com', 'SUSANTA-SS', 'ss#math21', '$2y$10$LN5LOULyf4CCV3C65tGSleYjUzL00LNr3yLZv03MuAIu6lk.Yi8pe', '', '1', '2023-02-09 14:14:32', '2', '13', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('50', '63', 'Prabal Sarkar', 'prabal', '', 'Mathematics', '13', 'dchcollege@yahoo.com', 'PRABAL-PS', 'ps#math22', '$2y$10$UqBazBEd3.10CXIIx/oueuwRcT5JAJKdBVeam/UKsLpKGJgEzJDKy', '', '1', '2023-02-09 14:15:58', '2', '13', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('51', '1306', 'Sougato Marik', 'sougato', '', 'Mathematics', '13', 'dchcollege@yahoo.com', 'SOUGATO-SM', 'sm#math23', '$2y$10$WPjwwZt46dq7WkEd0gMrguXaph5p9AWbJOKVVVZ86BE2cSI28rhW6', '', '1', '2023-02-09 14:16:41', '2', '13', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('52', '11', 'Tapasree Ghosh', 'tapasree', '', 'English', '2', 'dchcollege@yahoo.com', 'TAPASREE-TG', 'tap#eng21', '$2y$10$s.iYjqiCZPFWMO5aHJ808uygpslteQIBVYSOeNCoPdUNe8IN/g7G2', '', '1', '2023-02-09 15:08:52', '2', '2', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('53', '907', 'Manasi Bhunia Mal', 'manasi', '', 'Geography', '9', 'dchcollege@yahoo.com', 'MANASI-BHM', 'man#geo22', '$2y$10$FhBGegnlxS91z0zZXL0zgOcfJm5F/L.xn/lY.tfpPaCWupacILlni', '', '1', '2023-02-09 15:11:47', '2', '9', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('54', '1102', 'Satyabrata Sahoo', 'satyabrata', '7980548100', 'Physics', '11', 'dchcollege@yahoo.com', 'SS', 'ss#physics01', '$2y$10$p9tEvkOwmT2hgqZ7H26it.596nz3XloTCbBqTZrChqhM9DnW6Tnnm', '', '1', '2023-02-09 15:52:23', '2', '11', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('55', '49', 'Abhijit Pathak', 'abhijit', '9748179794', 'Economics', '10', 'dchcollege@yahoo.com', 'ABHIJIT-AP', 'ap#eco20', '$2y$10$PZlYpV6Zhkzgc96OCK5cieylrTAfE94Ffwjcss/B9Bt90z5g49V7O', '', '1', '2023-02-09 16:07:11', '2', '10', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('56', '702', 'Rajyashree Halder', 'rajyashree', '9564715846', 'Education', '7', 'dchcollege@yahoo.com', 'RAJYASHREE-RH', 'raj#edu21', '$2y$10$SyuRXpw3C9uybHXCMDg4iuH6Mn4rkI5j/NyZz1.R.ZtXiHyq6g5ae', '', '1', '2023-02-10 11:09:15', '2', '7', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('57', '706', 'Moumita Mondal', 'moumita', '', 'Education', '7', 'dchcollege@yahoo.com', 'MOUMITA-MM', 'mou#edu22', '$2y$10$BdLBOlUtcifaO4BDQRrOIu3VM54XQ7OCNRggr8DGuoo7nuaTxWFsm', '', '1', '2023-02-10 11:32:30', '2', '7', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('58', '705', 'Smriti Manna', 'smriti', '', 'Education', '7', 'dchcollege@yahoo.com', 'SMRITI-SM', 'sm#edu23', '$2y$10$nSljPYp97cnxNBFyoVFQEOtR.w0M8st0snUdhFqLdz6FvRyW5MIEW', '', '1', '2023-02-10 11:33:42', '2', '7', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('59', '1207', 'Subodh Kr. Sahoo', 'subodh', '6295802882', 'Chemistry', '12', 'dchcollege@yahoo.com', 'SUBODH-SKS', 'sub#chem21', '$2y$10$IdSfTW1ijk/eGA/yhoIKDuieD6hrFJ620z7MfqtBGI4K5.86zrH76', '', '1', '2023-02-10 11:41:44', '2', '12', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('60', '1206', 'Dipanwita Maity', 'dipanwita', '', 'Chemistry', '12', 'dchcollege@yahoo.com', 'DIPANWITA-DM', 'dip#chem22', '$2y$10$11UqmwJF7wb2bQm30pcYSe8ckReIEB/eiLkUFEPpbpE8KvFa2.SbG', '', '1', '2023-02-10 11:45:01', '2', '12', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('61', '1204', 'Madhusudan Das', 'madhusudan', '', 'Chemistry', '12', 'dchcollege@yahoo.com', 'MADHUSUDAN-MD', 'md#chem23', '$2y$10$WPeg/3nU44py6u3nbSyrXea4G5fOOaal5qAN2s/nwmprBtE7tYxsu', '', '1', '2023-02-10 11:46:14', '2', '12', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('63', '903', 'Priyanka', 'priyanka', '', 'Geography', '9', 'dchcollege@yahoo.com', 'PRIYANKA', 'pr#geo23', '$2y$10$qiAPMHbxJd3yJblW3ANAluEZW/rusGIay450b1GRVIG8Gs.QcJmxq', '', '1', '2023-02-10 12:13:31', '2', '9', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('64', '20', 'Sipra Halder', 'sipra', '9851610501', 'History', '4', 'dchcollege@yahoo.com', 'sipra', 'sip#his24', '$2y$10$74IGfQ0MsT2u4aHQxo18v.uUQWkYFC/Xs1OcZvhUhH.yLeQxIoEqC', '', '1', '2023-02-10 16:13:11', '2', '4', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('65', '302', 'Subhashis Bhattacharya', 'subhashis', '9748709807', 'Sanskrit', '3', 'dchcollege@yahoo.com', 'SUBHASISH-SB', 'sb#san23', '$2y$10$Cg/LH9HOku6x05bVrEC58.YaV/zFNwyUedaSKctVrBPkZtygcHYQK', '', '1', '2023-02-11 12:59:09', '2', '3', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('67', '301', 'Chandrima', 'chandrima', '9051265044', 'Sanskrit', '3', 'dchcollege@yahoo.com', 'chandrima', 'cg#sans22', '$2y$10$cxHSBTfkAFXF5wGM9CsTZOdslTsWmiEpJh/6MdS8mcvUTYTOFK3w6', '', '1', '2023-02-11 14:54:56', '2', '3', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('68', '305', 'Joydeb Dolui', 'joydeb', '', 'Sanskrit', '3', 'dchcollege@yahoo.com', 'joy-jd', 'jd#sans21', '$2y$10$GYeMiielvZ3PC9KvdnSzJ.LkfDo7gCYo1khMCOVU0kfAr1SUXedTm', '', '1', '2023-02-11 14:56:14', '2', '3', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('69', '504', 'Sudeshna Das', 'sudeshna', '', 'Political Science', '5', 'dchcollege@yahoo.com', 'sudeshna-sd', 'sd@pol23', '$2y$10$4W8HY7PGqdAsluI78WoL7uzXwWoT.UVnNc.xpZQoNu.2c13CEoHuq', '', '1', '2023-02-13 13:04:12', '2', '5', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('70', '11111', 'Sudeshna Moitra', 'sudeshna', '8697468620', 'Library', '21', 'dchcollege@yahoo.com', 'sm_library', 'SM@1234#', '$2y$10$5/cKAI1VPXsfekOGYc3DyOh/eQaQurPs8k54DRkD81c5an1UOkRte', '', '1', '2023-02-23 12:28:39', '2', '1', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('72', '13', 'Tarun Kumar Bag', 'tarun', '8910037519', 'English', '2', 'dchcollege@yahoo.com', 'Tarun-TKB', 'tb#eng21', '$2y$10$dHTvTgvIwlgXoNadTXYSIuAaDYd6YqzUwg01toMdOw5BhWgBp48Ly', '', '1', '2023-03-01 12:45:58', '2', '2', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('73', '171', 'RASIDUL KARIM', 'rasidul', '9083095705', 'Computer Science', '17', 'dchcollege@yahoo.com', 'rasidul-rk', 'rk@comp', '$2y$10$mMgBh7PPHrAuuZCxqN1SYuSsWmam7Wwe4hCzIFW4MxISWFh76vXla', '', '1', '2023-03-21 13:05:11', '2', '17', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('74', '1901', 'Sreeparna Ghose', 'sreeparna', '', 'Sociology', '20', 'sreeparna.ghose03@gmail.com', 'sreeparna', 'sree@soc1', '$2y$10$gy3hxOCwp54i4wVpJxNcc.9FCn.diZ0yycZOwptuMcd1DLIu/6P4W', '', '1', '2023-08-29 16:39:28', '2', '20', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('75', '2001', 'Sreerupa Ghose', 'sreerupa', '', 'Psychology', '19', 'sree17rupa@gmail.com', 'sreerupa', 'sree@psy1', '$2y$10$NRpAyZcvLr7cn2bo1NuR2.XQdNlFR442sPM8pMsOTnCNmwsBis3F2', '', '1', '2023-08-29 16:40:48', '2', '19', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('76', '1111', 'Nur Jaman', 'nur', '9717974276', 'Physics', '11', 'nurjaman@dchcollege.org', 'nurjaman', 'tb#eng21', '$2y$10$GrZNmTqMgcpaULJiWrE/bew3xg3hMINOvVE79R/c0m34D6.kUeeie', '', '1', '', '2', '11', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('77', '649', 'Nandita Pradhan', 'nandita', '', 'Economics', '10', '', 'nandita', 'Nandita@25#', '$2y$10$kB7SkGgSnosrDNntgo93YOzsJFbcxIOLUDtA6lXFgQTVWLRKIEdGW', '', '1', '', '2', '10', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('78', '48', 'Shyamal Kumar Bandyopadhyay', 'shyamal', '9433501282\r\n', 'Economics', '10', '', 'shyamalkrb', 'Shyamal@25#', '$2y$10$PBfkVoCWDL4j8TxgGZyqFerpw7poOKajA4RE.6myHtpBOgZt3Atcy', '', '1', '', '2', '10', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('79', '22', 'Anup Mandal', 'anup', '9734047126', 'History', '4', '', 'anupmandal', 'Anup@25#', '$2y$10$DDnp3SMHrgbGa1XoSIb7jeshVOgQkAK7/c1klThsxpdLjGjFsZnfa', '', '1', '', '2', '4', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('80', '23', 'Delowar Hossain Mollah', 'delowar', '', 'History', '4', '', 'delowar', 'Delowar@25#', '$2y$10$yzBLPJAGqKZgga3RnQ7.Luyqcc5UzGxCGuMJaVadL/lpeDT6IweJC', '', '1', '', '2', '4', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('81', '503', 'Sayanti Halder', 'sayanti', '8617228782\r\n', 'Political Science', '5', '', 'sayanti', 'Sayanti@25#', '$2y$10$SlvkCSABRmzNIz79KRXAGeaGROWGR5V4YjK25at8o3Xu9dQlf.u0.', '', '1', '', '2', '5', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('82', '505', 'Kaushik Das', 'kaushik', '9732586985', 'Political Science', '5', '', 'kaushik', 'KaushiK@pol#', '$2y$10$f34hiTj0f7heqLIZbc9rN.nJSISSDTVmiAicahUjxNmJN2mm00yki', '', '1', '', '2', '5', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('83', '603', 'Tusi Bhattacharya', 'tusi', '8910122987', 'Philosophy', '6', '', 'tusi', 'Tusi@phil#', '$2y$10$uL7goQLRP25rfobHVJRiguiYCk53xD0fajq6lUGrT5WeLozi3XxHq', '', '1', '', '2', '6', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('84', '42', 'Supriti Das', 'supriti', '', 'Physical Education', '8', '', 'supriti', 'Supriti@physed#', '$2y$10$Q.w8Zvy6yCfPAZRPGOlEh.M7.GAjlU3iM2uBaaCT8i8gI6dxdifHS', '', '1', '', '2', '8', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('85', '41', 'Biswajit Majhi', 'biswajit', '8768609616', 'Physical Education', '8', '', 'biswajit', 'Biswajit@25#', '$2y$10$BC3dzOzz4AnrvLfTnS8Q9uzVnlZbs2K4Cx7CQhMa1Ol/mFb3QE9qS', '', '1', '', '2', '8', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('86', '1653', 'Abhishek subba', 'abhishek', '', 'Zoology', '14', '', 'abhishek', 'Abhishek@25#', '$2y$10$yxomZwyi1H9I7aqy5KMhWO5kcwdeZeVF40tninI.ApGMaqUyuV05S', '', '1', '', '2', '14', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('87', '172', 'Samiran Sengupta', 'samiran', '9831955516', 'Computer Science', '17', '', 'samiran', 'Samiran@comp#', '$2y$10$dlIZypZG8RnoYPo5Qso/l.qJCud3sdKL6NxsYNfkovL86Kor81Zne', '', '1', '', '2', '17', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('88', '76', 'Subhasis Chakravarty', 'subhasis', '9433105887', 'Commerce', '18', '', 'subhasis_sc', 'Subhasis@25#', '$2y$10$8IhaDisvelJTJvx2cuFRdeQEObr/HZiqWs/.BCLDof2DVAmO4Bgze', '', '1', '', '2', '18', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('89', '641', 'Arup Ratan Misra', 'arup', '9474577686', 'Commerce', '18', '', 'arup_rm', 'AruP@25#', '$2y$10$Ah6h/oe2rSpG0lwfSCzZnel/Hb4qNc9V8Roo92.l2Q2DDUq8VJ7dO', '', '1', '', '2', '18', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('90', '1108', 'Ripon Sk', 'ripon', '80133 30542', 'Physics', '11', '', 'ripon', 'Ripon@physics#', '$2y$10$Bo3av3UuDuRNGowvGYaFauQYx4BFm93o.876ao7v4/Hg7sx6Ug0R6', '', '1', '', '2', '11', '1', '0');
INSERT INTO `admin_users` (`admin_id`, `fac_id`, `name`, `nickname`, `mobilenumber`, `department`, `dept_id`, `email`, `username`, `password_text`, `password`, `otp`, `is_verified`, `created_date`, `usergroup`, `deptgroup`, `status`, `is_superuser`) VALUES ('91', '642', 'Monica Mahali', 'Monica Mahali', '8918018126', 'Commerce', '18', '', 'monica', 'monica@25##', '$2b$12$HsQUFsqyt8IS0npu4WPqV.i1tePE9ewJIyx0zpiNTwZvAbmcP9ZrW', '123456', '1', '', '0', '0', '1', '');

